// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjfxx3A8DHwoCwffDH3h5cnfxHRikLzQI',
    appId: '1:620012359691:web:677efab3ffbdfc2e73770e',
    messagingSenderId: '620012359691',
    projectId: 'alikay-shop',
    authDomain: 'alikay-shop.firebaseapp.com',
    storageBucket: 'alikay-shop.appspot.com',
    measurementId: 'G-E6MDDTDY2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe6zM-5CnYYEPAw_9amujlZPR9iGkjfB8',
    appId: '1:620012359691:android:3ef8ec5df6c0dff273770e',
    messagingSenderId: '620012359691',
    projectId: 'alikay-shop',
    storageBucket: 'alikay-shop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtSaW7GZ0_Gv8XLlDvxjXDnZI10IFXe-A',
    appId: '1:620012359691:ios:5a579f898e2db8ea73770e',
    messagingSenderId: '620012359691',
    projectId: 'alikay-shop',
    storageBucket: 'alikay-shop.appspot.com',
    iosBundleId: 'com.example.alikayShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtSaW7GZ0_Gv8XLlDvxjXDnZI10IFXe-A',
    appId: '1:620012359691:ios:f3019be062d8d48673770e',
    messagingSenderId: '620012359691',
    projectId: 'alikay-shop',
    storageBucket: 'alikay-shop.appspot.com',
    iosBundleId: 'com.example.alikayShop.RunnerTests',
  );
}
